---
name-template: "promtail $RESOLVED_VERSION"
tag-template: "promtail.$RESOLVED_VERSION"
tag-prefix: "promtail."
include-paths:
  - "promtail"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
no-changes-template: "- No changes"
sort-direction: ascending

autolabeler:
  - label: "documentation"
    files:
      - "**/*.md"
  - label: "enhancement"
    files:
      - "promtail/**/*"
  - label: "maintenance"
    files:
      - ".github/**/*"
      - ".vscode/**/*"

## Defaults

categories:
  - title: "🚨 Breaking changes"
    labels:
      - "breaking-change"
  - title: "✨ New features"
    labels:
      - "new-feature"
  - title: "🐛 Bug fixes"
    labels:
      - "bugfix"
  - title: "🚀 Enhancements"
    labels:
      - "enhancement"
      - "refactor"
      - "performance"
  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
      - "ci"
  - title: "📚 Documentation"
    labels:
      - "documentation"
  - title: "🌎 Translations"
    labels:
      - "translations"
  - title: "⬆️ Dependency updates"
    labels:
      - "dependencies"

version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "new-feature"
  patch:
    labels:
      - "bugfix"
      - "chore"
      - "ci"
      - "dependencies"
      - "documentation"
      - "enhancement"
      - "performance"
      - "refactor"
  default: patch

template: |
  ## What’s changed
  $CHANGES
