---
build_from:
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:7.8.3
  amd64: ghcr.io/hassio-addons/debian-base/amd64:7.8.3
codenotary:
  signer: andressomadossi@home-assistant.io
  base_image: notary@home-assistant.io
labels:
  maintainer: "andressomadossi <andressomadossi@home-assistant.io>"
  org.opencontainers.image.authors: "andressomadossi <andressomadossi@home-assistant.io>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Grafana Promtail"
  org.opencontainers.image.url: https://github.com/andressomadossi/home-assistant-addons
  org.opencontainers.image.source: https://github.com/andressomadossi/home-assistant-addons/grafana-promtail
  org.opencontainers.image.documentation: https://github.com/andressomadossi/home-assistant-addons/grafana-promtail/README.md
  org.opencontainers.image.created: "2024-03-10T19:17:01Z"
  org.opencontainers.image.revision: 72a8b7a288baac5e2629f6f72ae0e41d9a0e4d68
  org.opencontainers.image.version: 3.0.8
