---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.io/home-assistant/amd64-base:3.22"
codenotary:
  signer: andressomadossi@home-assistant.io
  base_image: notary@home-assistant.io
labels:
  maintainer: "andressomadossi <andressomadossi@home-assistant.io>"
  org.opencontainers.image.authors: "andressomadossi <andressomadossi@home-assistant.io>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: grafana-loki"
  org.opencontainers.image.url: https://github.com/andressomadossi/home-assistant-addons
  org.opencontainers.image.source: https://github.com/andressomadossi/home-assistant-addons/grafana-loki
  org.opencontainers.image.documentation: https://github.com/andressomadossi/home-assistant-addons/grafana-loki/README.md
  org.opencontainers.image.created: "2024-03-10T19:15:17Z"
  org.opencontainers.image.revision: 6f94e84eed28ca505dc972a24573789ec112fb6c
  org.opencontainers.image.version: 3.5.1
