---
name: Grafana Loki
version: 3.5.3
slug: grafana-loki
description: Grafana Loki is a horizontally-scalable, highly-available, multi-tenant log aggregation system inspired by Prometheus
arch:
  - aarch64
  - amd64
image: "ghcr.io/andressomadossi/ha-addons-loki-{arch}"
url: https://github.com/andressomadossi/home-assistant-addons/tree/master/grafana-loki
startup: system
init: false
ports:
  3100/tcp: 3100
ports_description:
  3100/tcp: Loki listen port
panel_icon: mdi:router-network
map:
  - config
  - share/loki/data:/data/loki
options:
  days_to_keep: 30
  log_level: info
schema:
  days_to_keep: int(1,)?
  config_path: str?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
