---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"
codenotary:
  signer: homeassistant@blmx.de
  base_image: notary@home-assistant.io
labels:
  maintainer: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.authors: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: unpoller"
  org.opencontainers.image.url: https://github.com/bluemaex/home-assistant-addons
  org.opencontainers.image.source: https://github.com/bluemaex/home-assistant-addons/unpoller
  org.opencontainers.image.documentation: https://github.com/bluemaex/home-assistant-addons/unpoller/README.md
  org.opencontainers.image.created: "2023-08-07T19:14:16Z"
  org.opencontainers.image.revision: 9c3b89c45a38f434ea217d7a9185e3576e0a3475
  org.opencontainers.image.version: 3.0.5
