---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "21 4 * * *"
  workflow_dispatch:

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/labels.yaml@main
