---
name: Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  find:
    runs-on: ubuntu-latest
    name: 📢 Find changed addons
    outputs:
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: ⤵️ Check out the repository
        uses: actions/checkout@v3.5.3
      - name: 🗝️ Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1
      - name: 🚀 Find add-on directories
        id: addons
        uses: home-assistant/actions/helpers/find-addons@master
      - name: 🦺 Get changed add-ons
        id: changed_addons
        run: |
          declare -a changed_addons
          for addon in ${{ steps.addons.outputs.addons }}; do
            if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon ]]; then
              if [[ ! "${changed_addons[@]}" =~ $addon ]]; then
                changed_addons+=("\"${addon}\",");
              fi
            fi
          done

          changed=$(echo ${changed_addons[@]} | rev | cut -c 2- | rev)

          if [[ -n ${changed} ]]; then
            echo "Changed add-ons: $changed";
            echo "changed=true" >> $GITHUB_OUTPUT;
            echo "addons=[$changed]" >> $GITHUB_OUTPUT;
          else
            echo "No add-on had any monitored files changed (${{ env.MONITORED_FILES }})";
          fi

  lint-addon:
    name: 🔍 Lint add-on ${{ matrix.path }}
    runs-on: ubuntu-latest
    needs: find
    if: needs.find.outputs.changed == 'true'
    strategy:
      matrix:
        path: ${{ fromJson(needs.find.outputs.changed_addons) }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3.5.3
      - name: 🚀 Run Home Assistant Add-on Lint
        uses: frenck/action-addon-linter@v2.13
        with:
          path: "./${{ matrix.path }}"

  lint-shellcheck:
    name: 🔍 Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: 🚀 Run Shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: -s bash

  lint-markdown:
    name: 🔍 Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: 🚀 Run mdl
        uses: actionshub/markdownlint@v3.1.3

  lint-json:
    name: 🔍 JSON Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: 🚀 Run JQ
        run: |
          shopt -s globstar
          cat **/*.json | jq '.'

  lint-yamllint:
    name: 🔍 YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: 🚀 Run YAMLLint
        uses: frenck/action-yamllint@v1.4

  lint-prettier:
    name: 🔍 Prettier
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: 🚀 Run Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write **/*.{json,js,md,yaml,yml}
